### ISSUE TITLE
3-finger tap

### ISSUE THREAD

**Issue by anbroid** [daveriedstra/libinput-gestures#3]
3-finger drag works great, thank you! I'm using it with XFCE's "move window" shortcut in Window Manager settings, which allows me to do 3 window drag with the pointer ANYWHERE in the window, not just the title bar!
gesture swipebegin all 3 xdotool key alt+F7
gesture swipeend all 3 xdotool key alt+F7
gesture swipeupdate all 3 xdotool mousemove_relative -- x y
Very happy with this!

Is there a way or can you implement a way to do 3-finger tap for middle-click (paste) ?
With touchegg I used to do: gesture type="TAP" fingers="3" direction="", action type="MOUSE_CLICK">BUTTON=2
Looking for something similar here.
Could you add 3fingertap and 4fingertap gestures so we can call xdotool with them ?
Thank you!

**Comment by daveriedstra** [comment]
Glad to see you're getting use out of this, @anbroid! In my own configuration, I use a modifier key for window drag and three-finger middle click still works. (This is on GNOME with xinput tap-to-click enabled)

Adding a click event looks non-trivial, as they don't appear in the `libinput debug-events` output this utility uses. Is there another way to get the behaviour you're looking for? Are you using tap-to-click?

**Comment by anbroid** [comment]
I could already tap to click, but didn't see a setting for that. You gave me a hint however, so I found these settings for Xorg.conf and now I can do 3 finger tap for click:
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        MatchProduct "HTX"
        Driver "libinput"
        Option "Tapping" "on"
EndSection

BTW I'm using a USB touchpad on my desktop sold as Arkscan TP01 or Jelly Comb Touchpad, both appear as "HTX ..." and work the same. Wonderful device, it's like a cheap wired version of the magic trackpad. I'm all set, everything works including 3 finger drag anywhere in the window (makes things so comfortable) and 1 / 2 / 3 finger taps. Thanks for your help !
