### ISSUE TITLE
How to LockedDrags when using 3 finger drag?

### ISSUE THREAD

**Issue by duchengyao** [daveriedstra/libinput-gestures#4]
Thanks for your project!

When dragging for long distance , I have to drag more times. So, how to add feature for LockedDrags and LockedDragTimeout.

BTW, can I `set drag speed` or `enable pointer acceleration` when using 3-finger drag?

Thanks so much!

**Comment by daveriedstra** [comment]
Interesting idea, thank you for mentioning it. This feature is not currently present and I won't be implementing it here as I'm working on [other solutions](https://github.com/daveriedstra/draggy) for 3fd. I'll keep it in mind for these other projects though, and if someone wants to make a PR here I'll definitely take a look.

**Comment by duchengyao** [comment]
Could you please add the LockedDrags feature in your new solution?

Thanks

**Comment by daveriedstra** [comment]
@duchengyao Yep! I'm working on a few other things at the moment but I've opened an [issue](https://github.com/daveriedstra/draggy/issues/1) there to remind myself.

Since this won't be happening here, I'll close this issue.
