### ISSUE TITLE
3 fingr drag in chrome

### ISSUE THREAD

**Issue by cpphey** [daveriedstra/libinput-gestures#6]
@daveriedstra I having trouble copying text selected with a 3 finger scroll.

- I am using gnome with xorg
- I am using 2 finger scrolling from the gnome settings also
- without libgestures, I could tap with two fingers and see the menu in chrome which let me copy text show up
- I can select text in chrome with 3 fingers. This is from your repo

However the issue is after selecting the text it, the browser somehow goes back to the previous page.

` gesture swipebegin all 3 xdotool mousedown 1`
`gesture swipeend all 3 xdotool mouseup 1`
`gesture swipeupdate all 3 xdotool mousemove_relative -- x y `

**Comment by daveriedstra** [comment]
Hi @cpphey, sorry for the delay. This looks like a configuration issue. The three-finger drag feature overlaps / conflicts with the `gesture swipe` features, so you should deactivate or remove those from your configuration.
